name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * *'
  
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_UPDATED_DATE : "False"
          DEBUG_LOGGING : "False"
          LOCALE: "en"
